name: OurWorldPlugin
main: dns.mods.OurWorldPlugin
version: 1.2

commands:
  onblock:
    description: Shows the type of block you're standing on
    usage: /onblock [new block type]
  seeblock:
    description: What I am looking at?
  lightning:
    description: Strike lightning upon your enemies!
  explosion:
    description: Create an explosion
    usage: /explosion [explosion size]
