name: AboutMePlugin
version: 1.1
main: dns.mods.AboutMePlugin

commands:
  myname:
    description: Says my name
  mystats:
    description: Shows health and food levels
  heal:
    description: Heal yourself!
  mylocation:
    description: Shows my location
  jump:
    description: Jump!
  faster-speed:
    description: Fast walkspeed!
  normal-speed:
    description: Normal walkspeed!
  slower-speed:
    description: Slow walkspeed!
  level-up:
    description: Level up!
  level-down:
    description: Level down!
  fire-ticks:
    description: Fire ticks
  vacio:
    description: Reduce energy
  armor:
    description: Add super armor!
  hearts:
    description: Add hearts
    usage: /hearts [num hearts]
  absortion:
    description: Set absortion
    usage: /absortion [num hearts]
  deathloc:
    description: Go to previous death location
    usage: /deathloc
